floral-fusion/ViewComponents/FootersViewComponent.cs
using Microsoft.AspNetCore.Mvc;

[ViewComponent]
public class FootersViewComponent : ViewComponent
{
    public IViewComponentResult Invoke()
    {
        return View("Default");
    }
}

floral-fusion/ViewComponents/HeadersViewComponent.cs
using System.Xml;
using Microsoft.AspNetCore.Mvc;

[ViewComponent]
public class HeadersViewComponent : ViewComponent
{
    public IViewComponentResult Invoke(string name)
    {
        var user = Request?.Cookies["User"];
        int CartCount = 0;
        if (user != null)
        {
            var cartItem = new XmlDocument();
            cartItem.Load("./database/cartitem.xml");
            var nodes = cartItem?.SelectNodes("CartData/Item") ?? null;
            if (nodes != null)
            {
                foreach (XmlNode Item in nodes)
                {
                    Console.WriteLine();
                    if (Item.SelectSingleNode("user")?.InnerText == user)
                    {
                        CartCount++;
                    }
                }
            }
        }
        return View("Default", user +"|"+ CartCount.ToString());
    }
}

floral-fusion/Views/Shared/_Layout.cshtml
@{
    ViewData["NAME"] = "Floral Fusion Express";
}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Floral Fusion Express</title>
    @* <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" /> *@
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/tailwind/dist/output.css" />
    <script src="/_framework/aspnetcore-browser-refresh.js"></script>
    @* <link rel="stylesheet" href="~/floral_fusion.styles.css" asp-append-version="true" /> *@
</head>

<body>
    @if(Url?.Action()?.Split("/").Length > 1 && Url?.Action()?.Split("/")[1] == "Admin"){
        @await Component.InvokeAsync("AdminHeaders")
    }else{
        @await Component.InvokeAsync("Headers")
    }
    <div>
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    @await Component.InvokeAsync("Footers")
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>